# Generated by Django 5.2.5 on 2025-08-25 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Posts', '0001_initial'),
        ('User', '0010_alter_user_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotflicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('new_message', 'Новое сообщение')], max_length=64, verbose_name='Короткий код')),
                ('name', models.CharField(max_length=64, verbose_name='Человекочитаемое поле')),
                ('icon', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Notflication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в:')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано ли сообщение')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notflication_message', to='User.message')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notflication_post', to='Posts.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notflication', to=settings.AUTH_USER_MODEL)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notflication_from_type', to='Notifications.notflicationtype')),
            ],
        ),
    ]
