# Generated by Django 5.2.5 on 2025-08-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_bio_user_created_at_user_created_at_formatted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.CharField(blank=True, default='Не работает', max_length=20, null=True),
        ),
    ]
