# Generated by Django 5.2.5 on 2025-08-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/anonim.jpg', upload_to='images/'),
        ),
    ]
