# Generated by Django 5.2.5 on 2025-08-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='avatar',
        ),
    ]
