# Generated by Django 5.2.5 on 2025-08-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_rename_image_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at_formatted',
        ),
    ]
