# Generated by Django 5.2.5 on 2025-08-25 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_message_chat_alter_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Группа или нет'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_users', to='User.chat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Вошёл в:'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='User.chat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано в:'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='Не указано', max_length=128, verbose_name='Описание профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='Не указано', max_length=32, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Тег пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Web-site'),
        ),
        migrations.AlterUniqueTogether(
            name='chatuser',
            unique_together={('chat', 'user')},
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['is_group'], name='User_chat_is_grou_9fafc0_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['created_at'], name='User_chat_created_5e7966_idx'),
        ),
        migrations.AddIndex(
            model_name='chatuser',
            index=models.Index(fields=['chat', 'user'], name='User_chatus_chat_id_e22862_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'send_at'], name='User_messag_chat_id_a3c0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'send_at'], name='User_messag_user_id_092746_idx'),
        ),
    ]
