# Generated by Django 5.2.5 on 2025-08-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_chat_is_group_alter_chatuser_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Тег пользователя'),
        ),
    ]
