# Generated by Django 5.2.5 on 2025-08-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.BigIntegerField(default=0, verbose_name='Шейры'),
        ),
    ]
