# Generated by Django 5.2.5 on 2025-08-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_post_likes_post_shares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='text',
        ),
    ]
