# Generated by Django 5.2.5 on 2025-08-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_rename_name_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='shares',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Шейры'),
        ),
    ]
