# Generated by Django 5.2.5 on 2025-08-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_alter_post_likes_alter_post_shares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
    ]
