# Generated by Django 5.2.5 on 2025-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_rename_author_id_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='file_url',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Путь до файла'),
        ),
    ]
