# Generated by Django 5.2.5 on 2025-08-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_alter_postimage_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='file_url',
            field=models.ImageField(blank=True, upload_to='images/posts', verbose_name='Путь до файла'),
        ),
    ]
