# Generated by Django 5.2.5 on 2025-09-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_alter_postimage_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
